# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Hannah Tipperman
email: htipperman@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Welcome to my personal website! I'm a sophomore studying CS at Brown University, and I'm always exited to talk about anything from iOS programming to women in STEM to starting a non-profit. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  htipperman

# Build settings
markdown: kramdown
